/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gfjbwfolopksznmweggw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmamJ3Zm9sb3Brc3pubXdlZ2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNDY0NzEsImV4cCI6MjA5MTgyMjQ3MX0.iwj6x1K_Mgpn24F2di-fV6EZGvQ_NSMu-3Wo5MPDls4"